#!/bin/sh

set -e

manyrepos_dir=.many
manyrepos_branch=master
metarepo_branch=meta

init() {
  ls $manyrepos_dir |
  while read project
  do
    git subtree add --prefix=$project $manyrepos_dir/$project $manyrepos_branch
  done
}

sync() {
  ls $manyrepos_dir |
  while read project
  do
    pull $project
    push $project
  done
}

pull() {
  project=$1
  git subtree pull --prefix=$project $manyrepos_dir/$project $manyrepos_branch
}

push() {
  project=$1
  git subtree push --prefix=$project $manyrepos_dir/$project $metarepo_branch
  pushd $manyrepos_dir/$project
  git merge $metarepo_branch --no-commit
  git commit --no-edit
  popd
}

print_usage() {
  echo "Usage:"
  echo
  echo "$0 [subcommand]"
  echo
  echo "Supported subcommands:"
  echo
  echo "  init"
  echo "  sync"
}

usage() {
  print_usage 1>&2
  exit 1
}

command=$1

if [ "$command" = "" ]; then
  usage
fi

shift

case $command in
   init)
      init $@
      ;;
   sync)
      sync $@
      ;;
   *)
      usage
      ;;
esac
