#!/bin/sh

set -e

manyrepos_dir=.many

init() {
  ls $manyrepos_dir |
  while read path
  do
    git subtree add --prefix=$path $manyrepos_dir/$path master
  done
}

sync() {
  echo sync
}

print_usage() {
  echo "Usage:"
  echo
  echo "$0 [subcommand]"
  echo
  echo "Supported subcommands:"
  echo
  echo "  init"
  echo "  sync"
}

usage() {
  print_usage 1>&2
  exit 1
}

command=$1

if [ "$command" = "" ]; then
  usage
fi

shift

case $command in
   init)
      init $@
      ;;
   sync)
      sync $@
      ;;
   *)
      usage
      ;;
esac
