# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install: R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

jobs:
  include:
  - addons:
      apt:
        packages:
        - libgoogle-perftools-dev
    env:
    - KIND=apt
    - BUILD_PKGDOWN=true
  - addons:
      apt:
        packages:
        - libunwind8-dev
    env:
    - KIND=github
    before_install:
    - ( cd /tmp && git clone --depth 1 https://github.com/gperftools/gperftools.git )
    - ( cd /tmp/gperftools && ./autogen.sh && ./configure --prefix=${HOME} && make && make install )
    - mkdir -p ~/.R
    - echo "PKG_CPPFLAGS = -I${HOME}/include" >> ~/.R/Makevars
    - echo "LDFLAGS := ${LDFLAGS} -shared -L${HOME}/lib" >> ~/.R/Makevars
    - echo "LD_RUN_PATH = ${HOME}/lib" >> ~/.R/Makevars
    - echo "export LD_RUN_PATH" >> ~/.R/Makevars

#services
services:
